#!/bin/sh /etc/rc.common
# Copyright aseracorp 2026
# description: Stop CosmosCloud + open LuCI if initial cosmos setup is not done within 2h
# processname: /bin/CosmosSetupWatchdog

START=99
STOP=01
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /bin/bash "/bin/CosmosSetupWatchdog"
        procd_set_param pidfile /var/run/CosmosSetupWatchdog.pid
        procd_set_param term_timeout 60
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
