#!/bin/sh /etc/rc.common
# if this scripts finds a file called reset in /boot, it factory resets / deletes all data
# Copyright aseracorp 2025

START=98
STOP=03

start() {
        if [ -f /boot/reset ]; then rm /boot/reset && firstboot -y && reboot && exit 0; fi
}

stop() {
        exit
}