#!/bin/sh /etc/rc.common
# Copyright aseracorp 2026
# description: workaround for lighthouse with changing IP
# processname: /bin/lighthouseCheck

START=99
STOP=01
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /bin/bash "/bin/lighthouseCheck"
        procd_set_param pidfile /var/run/lighthouseCheck.pid
        procd_set_param term_timeout 60
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn 150 10 10
        procd_close_instance
}