## This file contains files and directories that should
## be preserved during an upgrade

/etc/sysupgrade.conf
/opt/cosmos-config/
/opt/docker
/var/lib/cosmos
/etc/init.d/CosmosCloud
/etc/init.d/factoryReset
/etc/uci-defaults/99-cosmos-default
/bin/shutdown